version: '3.9'

services:
  dev-db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_PASSWORD: '123'
      MYSQL_DATABASE: dronesDB
      MYSQL_USER: development
    networks:
      - drones_net

networks:
  drones_net:
    name: drones_net
